### ISSUE TITLE
Mood Board

### ISSUE THREAD

**Issue by TamarZanzouri** [shenkarlab/Chakim#3]

**Comment by meiravron** [comment]
![mood_board](https://cloud.githubusercontent.com/assets/9407630/5606021/c715cdf4-9422-11e4-8822-f044e76bece1.png)
![mood_board2](https://cloud.githubusercontent.com/assets/9407630/5606022/c717cfe6-9422-11e4-8893-d8d4a2ec6081.png)
![mood_board3](https://cloud.githubusercontent.com/assets/9407630/5606023/c7189282-9422-11e4-8cbc-f18c95f236ad.png)
![mood_board4](https://cloud.githubusercontent.com/assets/9407630/5606026/c7202556-9422-11e4-9458-096a8bd24807.png)
![mood_board5](https://cloud.githubusercontent.com/assets/9407630/5606024/c719c6e8-9422-11e4-88af-97de4a451a77.png)
![mood_board6](https://cloud.githubusercontent.com/assets/9407630/5606025/c71cda9a-9422-11e4-9e74-8469da746dd0.png)
![mood_board7](https://cloud.githubusercontent.com/assets/9407630/5606027/c73f84be-9422-11e4-857d-9c79486ce2fa.png)
![mood_board8](https://cloud.githubusercontent.com/assets/9407630/5606030/c744aee4-9422-11e4-9b1c-a989b3a8af7e.png)
![mood_board9](https://cloud.githubusercontent.com/assets/9407630/5606028/c742e2f8-9422-11e4-91e2-c333d42d6c9f.png)
![mood_board10](https://cloud.githubusercontent.com/assets/9407630/5606029/c743fa26-9422-11e4-86b9-6a2f0cbaaab6.png)
![mood_board11](https://cloud.githubusercontent.com/assets/9407630/5606031/c745fad8-9422-11e4-89bb-95eac5a4288f.png)
![mood_board12](https://cloud.githubusercontent.com/assets/9407630/5606032/c7471288-9422-11e4-9dd4-749246ab6453.png)
![mood_board13](https://cloud.githubusercontent.com/assets/9407630/5606033/c766c9de-9422-11e4-803d-a330a0ef04c4.png)
![mood_board14](https://cloud.githubusercontent.com/assets/9407630/5606034/c76bc2b8-9422-11e4-9824-8ba79baa6818.png)
