### ISSUE TITLE
תוסיפו את לוגו שנקר לדף הראשי

### ISSUE THREAD

**Issue by mushon** [shenkarlab/Chakim#33]
@shenkarlab/chakim 
אפשר גם בקטן, אבל חשוב שכל מי שפותח את זה יבין מיד שזה שת״פ עם שנקר.

**Comment by shaulams** [comment]
יהיה כתוב שם בטקסט

**Comment by mushon** [comment]
סבבה. אני רוצה שהלוגו יופיע לצד האיזכור של שנקר בטקסט.

**Comment by TamarZanzouri** [comment]
הוספתי את הלוגו של שנקר ב
gh-pages
עדכן אותי אם זאת הייתה כוונתך

**Comment by mushon** [comment]
סבבה
